[build]
  # Build command for the frontend
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables should be set in Netlify dashboard
# Go to: Site settings > Build & deploy > Environment variables
# Required variables:
# - VITE_API_URL (e.g., https://your-backend.railway.app/api/v1)
# - VITE_NODE_ENV (production or development)
#
# Optional variables (if features are used):
# - VITE_GOOGLE_CLIENT_ID
# - VITE_RAZORPAY_KEY_ID
# - VITE_CLOUDINARY_CLOUD_NAME
