[phases.setup]
nixPkgs = ["nodejs-18_x", "python39", "python39Packages.pip"]

[phases.install]
cmds = [
  "npm ci",
  "cd python-services && python -m venv venv",
  "cd python-services && ./venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

